### ISSUE TITLE
LibreOffice Can't Closed After Running LO-TC

### ISSUE THREAD

**Issue by raniaamina** [libreofficeid/LO-TC-GUI#4]
LibreOffice Version: 6.2.4.2 & 6.3.3.2.0+
LibreOffice Instalataion Method: Repository & Flatpak
Operating System: Debian Sid
Desktopn Enveronment: KDE Plasma (5.14.5)

Bug Description:
After running LibreOffice Theme Changer, LibreOffice can't be closed even i press close window button.

**Comment by artemtech** [comment]
@raniaamina kan terkait ini juga 😅

**Comment by fweng322** [comment]
It may be a bug of LibreOffice kf5 backend.

https://bugs.documentfoundation.org/show_bug.cgi?id=128710

using SAL_USE_VCLPLUGIN=gtk3 can run this extension

**Comment by raniaamina** [comment]
@fweng322 i think so, 
we have test in on Mac (by @princeofgiri), then use other backend (GTK) for running LibreOffice & LOTC, no problem found

**Comment by fweng322** [comment]
tdf#128710 has been fixed and will be available in 6.4.0.1 and 6.3.4.

https://bugs.documentfoundation.org/show_bug.cgi?id=128710#c9

**Comment by raniaamina** [comment]
waaa, thank @fweng322 :")
